<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  

  <head>
    
    <title>django.contrib.gis.gdal.error</title>
    <meta name="generator" content="pydoctor 22.2.0"> 
        
    </meta>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.75" />
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="apidocs.css" />
    <link rel="stylesheet" type="text/css" href="extra.css" />
</head>

  <body>

    <div id="banner" class="container">    
    <div>
        <a href="https://pydocbrowser.github.io/">Home</a>
        &gt; django-4.0.2 
        <!-- This is an important placeholder and will be 
            replaced by project name and version on building docs -->
        
        <!-- (<a href=""&gt;show all versions</a&gt;) -->
    </div>
</div>

    <nav class="navbar navbar-default">
  
  <div class="container">

    <div class="navbar-header">
      
      <div class="navlinks">
          <span class="navbar-brand">
            django <a href="index.html">API Documentation</a>
          </span>

          <a href="moduleIndex.html">
            Modules
          </a>

          <a href="classIndex.html">
            Classes
          </a>

          <a href="nameIndex.html">
            Names
          </a>
      </div>

    </div>
  </div>
</nav>

    

    <div class="container">

      <div class="page-header">
        <h1 class="module"><code><code><a href="index.html" class="internal-link">django</a></code><wbr></wbr>.<code><a href="django.contrib.html" class="internal-link" title="django.contrib">contrib</a></code><wbr></wbr>.<code><a href="django.contrib.gis.html" class="internal-link" title="django.contrib.gis">gis</a></code><wbr></wbr>.<code><a href="django.contrib.gis.gdal.html" class="internal-link" title="django.contrib.gis.gdal">gdal</a></code><wbr></wbr>.<code><a href="django.contrib.gis.gdal.error.html" class="internal-link" title="django.contrib.gis.gdal.error">error</a></code></code></h1>
        <div id="showPrivate">
          <button class="btn btn-link" onclick="togglePrivate()">Toggle Private API</button>
        </div>
      </div>

      <div class="categoryHeader">
        module documentation
      </div>

      <div class="extrasDocstring">
        <a href="https://github.com/pydocbrowser/pydocbrowser.github.io/tree/main/build/sources/django-4.0.2//django/contrib/gis/gdal/error.py" class="sourceLink">(source)</a>
        <p></p>
      </div>

      <div class="moduleDocstring">
        <div>This module houses the GDAL &amp; SRS Exception objects, and the
check_err() routine which checks the status code returned by
GDAL/OGR methods.</div>
      </div>

      <div id="splitTables">
        <table class="children sortable" id="id2373">
  
  
  <tr class="constant">
    
    <td>Constant</td>
    <td><code><a href="#CPLERR_DICT" class="internal-link" title="django.contrib.gis.gdal.error.CPLERR_DICT">CPLERR​_DICT</a></code></td>
    <td><span class="undocumented">Undocumented</span></td>
  </tr><tr class="constant">
    
    <td>Constant</td>
    <td><code><a href="#ERR_NONE" class="internal-link" title="django.contrib.gis.gdal.error.ERR_NONE">ERR​_NONE</a></code></td>
    <td><span class="undocumented">Undocumented</span></td>
  </tr><tr class="constant">
    
    <td>Constant</td>
    <td><code><a href="#OGRERR_DICT" class="internal-link" title="django.contrib.gis.gdal.error.OGRERR_DICT">OGRERR​_DICT</a></code></td>
    <td><span class="undocumented">Undocumented</span></td>
  </tr>
</table>
        

          
      </div>

      <div id="childList">

        <div class="baseconstant">
  
  
  <a name="django.contrib.gis.gdal.error.CPLERR_DICT">
    
  </a>
  <a name="CPLERR_DICT">
    
  </a>
  <div class="functionHeader">
    
    <span class="py-defname">CPLERR_DICT</span> =
    <a class="sourceLink" href="https://github.com/pydocbrowser/pydocbrowser.github.io/tree/main/build/sources/django-4.0.2//django/contrib/gis/gdal/error.py#L33">
      
      (source)
    </a>
  </div>
  <div class="functionBody">
    
    
    <div><p class="undocumented">Undocumented</p></div>
    <table class="valueTable"><tr class="fieldStart"><td class="fieldName">Value</td></tr><tr><td><pre class="constant-value"><code>{<wbr></wbr>1: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">AppDefined</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>2: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">OutOfMemory</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>3: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">FileIO</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>4: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">OpenFailed</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>5: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">IllegalArg</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>6: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">NotSupported</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>7: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">AssertionFailed</span><span class="rst-variable-quote">'</span>),
<span class="rst-variable-ellipsis">...</span></code></pre></td></tr></table>
  </div>
</div><div class="baseconstant">
  
  
  <a name="django.contrib.gis.gdal.error.ERR_NONE">
    
  </a>
  <a name="ERR_NONE">
    
  </a>
  <div class="functionHeader">
    
    <span class="py-defname">ERR_NONE</span>: <code><a href="https://docs.python.org/3/library/functions.html#int" class="intersphinx-link">int</a></code> =
    <a class="sourceLink" href="https://github.com/pydocbrowser/pydocbrowser.github.io/tree/main/build/sources/django-4.0.2//django/contrib/gis/gdal/error.py#L46">
      
      (source)
    </a>
  </div>
  <div class="functionBody">
    
    
    <div><p class="undocumented">Undocumented</p></div>
    <table class="valueTable"><tr class="fieldStart"><td class="fieldName">Value</td></tr><tr><td><pre class="constant-value"><code>0</code></pre></td></tr></table>
  </div>
</div><div class="baseconstant">
  
  
  <a name="django.contrib.gis.gdal.error.OGRERR_DICT">
    
  </a>
  <a name="OGRERR_DICT">
    
  </a>
  <div class="functionHeader">
    
    <span class="py-defname">OGRERR_DICT</span> =
    <a class="sourceLink" href="https://github.com/pydocbrowser/pydocbrowser.github.io/tree/main/build/sources/django-4.0.2//django/contrib/gis/gdal/error.py#L20">
      
      (source)
    </a>
  </div>
  <div class="functionBody">
    
    
    <div><p class="undocumented">Undocumented</p></div>
    <table class="valueTable"><tr class="fieldStart"><td class="fieldName">Value</td></tr><tr><td><pre class="constant-value"><code>{<wbr></wbr>1: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">Not enough data.</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>2: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">Not enough memory.</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>3: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">Unsupported geometry type.</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>4: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">Unsupported operation.</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>5: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">Corrupt data.</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>6: (<wbr></wbr><a href="django.contrib.gis.gdal.GDALException.html" class="internal-link" title="django.contrib.gis.gdal.GDALException">GDALException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">OGR failure.</span><span class="rst-variable-quote">'</span>),
 <wbr></wbr>7: (<wbr></wbr><a href="django.contrib.gis.gdal.SRSException.html" class="internal-link" title="django.contrib.gis.gdal.SRSException">SRSException</a>, <wbr></wbr><span class="rst-variable-quote">'</span><span class="rst-variable-string">Unsupported SRS.</span><span class="rst-variable-quote">'</span>),
<span class="rst-variable-ellipsis">...</span></code></pre></td></tr></table>
  </div>
</div>

      </div>
    </div>

    <footer class="navbar navbar-default">
  
  <div class="container">
    <a href="index.html">API Documentation</a> for django,
  generated by <a href="https://github.com/twisted/pydoctor/">pydoctor</a>
    22.2.0 at 2022-02-23 08:05:35.
  </div>
</footer>

    <script src="pydoctor.js" type="text/javascript"></script>

  </body>
</html>